language: cpp
sudo: required
dist: trusty
branches:
  only:
  - master
  - devel
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - qt4-dev-tools
      - libopenscenegraph-dev
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-system-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - libboost-regex-dev
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libqt4-opengl-dev libqtgui4 oxygen-icon-theme
- sudo apt-get install -qq liburdfdom-dev libomniorb4-dev omniorb-nameserver omniidl omniidl-python

script: .travis/build
